/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmangementsystems;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kmike
 */
public class HodPowers extends javax.swing.JFrame {

    /**
     * Creates new form HodPowers
     */
    public HodPowers() {
        initComponents();
         ButtonGroup buttongroup=new ButtonGroup();
        buttongroup.add(hodRadio);
         buttongroup.add(stdRadio);
         buttongroup.add(lecradio);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewstnts = new javax.swing.JLabel();
        viewlecs = new javax.swing.JLabel();
        labelAddauseer = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        UserReg = new javax.swing.JPanel();
        ussertf = new javax.swing.JTextField();
        userPass = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stdRadio = new javax.swing.JRadioButton();
        hodRadio = new javax.swing.JRadioButton();
        lecradio = new javax.swing.JRadioButton();
        editlecturer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editpane = new javax.swing.JPanel();
        mikePane = new javax.swing.JPanel();
        addUnits = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        unittf = new javax.swing.JTextField();
        lecturernumber = new javax.swing.JTextField();
        addlecturer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        usernametf = new javax.swing.JTextField();
        tnumber = new javax.swing.JTextField();
        submitLecs = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        lrecords = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lrecs = new javax.swing.JTable();
        lectsRecord = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lectsRecords = new javax.swing.JTable();
        studentsRec = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableStdsRecs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel9.setBackground(new java.awt.Color(153, 255, 255));
        jLabel9.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel9.setText("BrookStone schools  HOD ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(150, 150, 150))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("ALTER STDS");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("EDIT LECT'S");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        viewstnts.setText("VIEW STUDENTS");
        viewstnts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewstntsMouseClicked(evt);
            }
        });

        viewlecs.setText("VIEW LECTURERS");
        viewlecs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewlecsMouseClicked(evt);
            }
        });

        labelAddauseer.setText("ADD USERS");
        labelAddauseer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddauseerMouseClicked(evt);
            }
        });

        logoutbtn.setText("LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        jLabel13.setText("UNIT ASSIGNED");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewlecs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addComponent(labelAddauseer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewstnts)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(logoutbtn)
                            .addGap(9, 9, 9))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelAddauseer)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(viewstnts)
                .addGap(18, 18, 18)
                .addComponent(viewlecs)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(104, 104, 104)
                .addComponent(logoutbtn)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        main.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(102, 51, 0));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books-21849__480.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );

        main.add(home, "card5");

        UserReg.setBackground(new java.awt.Color(0, 102, 102));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("USER NAME");

        jLabel12.setText("PASSWORD");

        stdRadio.setText("stdent");

        hodRadio.setText("HOD");

        lecradio.setText("lecturer");

        javax.swing.GroupLayout UserRegLayout = new javax.swing.GroupLayout(UserReg);
        UserReg.setLayout(UserRegLayout);
        UserRegLayout.setHorizontalGroup(
            UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addGap(254, 254, 254))
            .addGroup(UserRegLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserRegLayout.createSequentialGroup()
                        .addComponent(stdRadio)
                        .addGap(30, 30, 30)
                        .addComponent(hodRadio)
                        .addGap(39, 39, 39)
                        .addComponent(lecradio))
                    .addGroup(UserRegLayout.createSequentialGroup()
                        .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(101, 101, 101)
                        .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ussertf)
                            .addComponent(userPass, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        UserRegLayout.setVerticalGroup(
            UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ussertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(87, 87, 87)
                .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(55, 55, 55)
                .addGroup(UserRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdRadio)
                    .addComponent(hodRadio)
                    .addComponent(lecradio))
                .addGap(47, 47, 47)
                .addComponent(addBtn)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        main.add(UserReg, "card6");

        editlecturer.setBackground(new java.awt.Color(255, 255, 153));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Assign units");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("AddLecturer");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        editpane.setBackground(new java.awt.Color(153, 255, 255));
        editpane.setLayout(new java.awt.CardLayout());

        mikePane.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout mikePaneLayout = new javax.swing.GroupLayout(mikePane);
        mikePane.setLayout(mikePaneLayout);
        mikePaneLayout.setHorizontalGroup(
            mikePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        mikePaneLayout.setVerticalGroup(
            mikePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        editpane.add(mikePane, "card4");

        addUnits.setBackground(new java.awt.Color(255, 255, 153));

        jLabel7.setText("unit name");

        jLabel8.setText("lecturerer number");

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUnitsLayout = new javax.swing.GroupLayout(addUnits);
        addUnits.setLayout(addUnitsLayout);
        addUnitsLayout.setHorizontalGroup(
            addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUnitsLayout.createSequentialGroup()
                .addGroup(addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUnitsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(63, 63, 63)
                        .addGroup(addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unittf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturernumber, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addUnitsLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(submit)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        addUnitsLayout.setVerticalGroup(
            addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUnitsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(unittf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(addUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lecturernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(71, 71, 71))
        );

        editpane.add(addUnits, "card3");

        addlecturer.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setText("teaching number");

        jLabel4.setText("first name");

        jLabel5.setText("username");

        jLabel6.setText("last name");

        submitLecs.setText("Submit");
        submitLecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLecsActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addlecturerLayout = new javax.swing.GroupLayout(addlecturer);
        addlecturer.setLayout(addlecturerLayout);
        addlecturerLayout.setHorizontalGroup(
            addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addlecturerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addlecturerLayout.createSequentialGroup()
                        .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernametf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addlecturerLayout.createSequentialGroup()
                        .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addlecturerLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addlecturerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(452, 452, 452))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addlecturerLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitLecs)
                .addGap(277, 277, 277))
        );
        addlecturerLayout.setVerticalGroup(
            addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addlecturerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(addlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitLecs)
                    .addComponent(delete))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        editpane.add(addlecturer, "card2");

        javax.swing.GroupLayout editlecturerLayout = new javax.swing.GroupLayout(editlecturer);
        editlecturer.setLayout(editlecturerLayout);
        editlecturerLayout.setHorizontalGroup(
            editlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editlecturerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(editlecturerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        editlecturerLayout.setVerticalGroup(
            editlecturerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editlecturerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main.add(editlecturer, "card4");

        lrecords.setBackground(new java.awt.Color(204, 255, 255));

        lrecs.setBackground(new java.awt.Color(255, 255, 255));
        lrecs.setForeground(new java.awt.Color(51, 102, 255));
        lrecs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(lrecs);

        javax.swing.GroupLayout lrecordsLayout = new javax.swing.GroupLayout(lrecords);
        lrecords.setLayout(lrecordsLayout);
        lrecordsLayout.setHorizontalGroup(
            lrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        lrecordsLayout.setVerticalGroup(
            lrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        main.add(lrecords, "card7");

        lectsRecord.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        lectsRecords.setBackground(new java.awt.Color(255, 255, 255));
        lectsRecords.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        lectsRecords.setForeground(new java.awt.Color(153, 255, 255));
        lectsRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        lectsRecords.setToolTipText("");
        lectsRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lectsRecordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lectsRecords);

        javax.swing.GroupLayout lectsRecordLayout = new javax.swing.GroupLayout(lectsRecord);
        lectsRecord.setLayout(lectsRecordLayout);
        lectsRecordLayout.setHorizontalGroup(
            lectsRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lectsRecordLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );
        lectsRecordLayout.setVerticalGroup(
            lectsRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lectsRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        main.add(lectsRecord, "card3");

        TableStdsRecs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TableStdsRecs);

        jLayeredPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout studentsRecLayout = new javax.swing.GroupLayout(studentsRec);
        studentsRec.setLayout(studentsRecLayout);
        studentsRecLayout.setHorizontalGroup(
            studentsRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsRecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        studentsRecLayout.setVerticalGroup(
            studentsRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentsRecLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        main.add(studentsRec, "card2");

        jPanel1.add(main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
         
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       AlterStudentsRecords adr=new AlterStudentsRecords();
       adr.show(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lectsRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lectsRecordsMouseClicked
       
      
    }//GEN-LAST:event_lectsRecordsMouseClicked

    private void viewlecsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewlecsMouseClicked
          try{
           String sql="SELECT * FROM `lecturersrecord`;";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            PreparedStatement ps=con.prepareStatement(sql);
          
             ResultSet rs= ps.executeQuery();
            lectsRecords.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
           
        
        
        
        main.removeAll();
        main.add(lectsRecord);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_viewlecsMouseClicked

    private void viewstntsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewstntsMouseClicked
        
        try{
           String sql="SELECT * FROM `records`;";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            PreparedStatement ps=con.prepareStatement(sql);
          
             ResultSet rs= ps.executeQuery();
             TableStdsRecs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
      
        main.removeAll();
        main.add(studentsRec);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_viewstntsMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         main.removeAll();
        main.add(editlecturer);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void labelAddauseerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddauseerMouseClicked
        main.removeAll();
        main.add(UserReg);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_labelAddauseerMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
          String utype=null;
        if (lecradio.isSelected()){
            utype="LECTURER";
        }else if (stdRadio.isSelected()){
            utype="STUDENT";
        } else if (hodRadio.isSelected()){
            utype="HOD";
        }
        
        try {

           Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            Statement stmt= con.createStatement();
            /* ps=con.prepareStatement("INSERT INTO `users`( `username`, `password`) VALUES (?,?)");
            ps.setString(2, admtf.getText());
            ps.setString(1, emailtf.getText());*/

           PreparedStatement ps=con.prepareStatement("INSERT INTO `users`( `username`, `password`, `usertype`) VALUES (?,?,?)");
            ps.setString(1,ussertf.getText());
            ps.setString(2, userPass.getText());
            ps.setString(3, utype);
           

            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "New user Created");
            }

        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
       this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {

           Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            Statement stmt= con.createStatement();
            /* ps=con.prepareStatement("INSERT INTO `users`( `username`, `password`) VALUES (?,?)");
            ps.setString(2, admtf.getText());
            ps.setString(1, emailtf.getText());*/

           PreparedStatement ps=con.prepareStatement("INSERT INTO `lecturingassignment` (`unitName`, `LECTUREID`) VALUES (?,?);");
            ps.setString(1,unittf.getText());
            ps.setString(2, lecturernumber.getText());
          
           

            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "New unit Lecturer registered");
            }

        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,"unit is alredy assigned");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void submitLecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLecsActionPerformed
        try {

           Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            Statement stmt= con.createStatement();
            PreparedStatement ps=con.prepareStatement("INSERT INTO `lecturersrecord`(`id`, `First Name`, `Last Name`, `username`) VALUES (?,?,?,?)");
            ps.setString(1,tnumber.getText());
            ps.setString(2, firstname.getText());
             ps.setString(3, lastname.getText());
              ps.setString(4, usernametf.getText());
           
           

            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "New user Created");
            }

        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_submitLecsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          editpane.removeAll();
         editpane.add(addlecturer);
          editpane.repaint();
         editpane.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       editpane.removeAll();
        editpane.add(addUnits);
       editpane.repaint();
      editpane.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      try{
           String sql="SELECT * FROM `lecturingassignment`; ";
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
            PreparedStatement ps=con.prepareStatement(sql);
          
             ResultSet rs= ps.executeQuery();
             lrecs.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
      
        main.removeAll();
        main.add(lrecords);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try{
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/mike","root","");
           PreparedStatement ps;
            ps=con.prepareStatement("DELETE FROM `lecturersrecord` WHERE `id`=?");

            ps.setString(1, tnumber.getText());

            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "DELETED");
            }

        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HodPowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HodPowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HodPowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HodPowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HodPowers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStdsRecs;
    private javax.swing.JPanel UserReg;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addUnits;
    private javax.swing.JPanel addlecturer;
    private javax.swing.JButton delete;
    private javax.swing.JPanel editlecturer;
    private javax.swing.JPanel editpane;
    private javax.swing.JTextField firstname;
    private javax.swing.JRadioButton hodRadio;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAddauseer;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton lecradio;
    private javax.swing.JPanel lectsRecord;
    private javax.swing.JTable lectsRecords;
    private javax.swing.JTextField lecturernumber;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel lrecords;
    private javax.swing.JTable lrecs;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mikePane;
    private javax.swing.JRadioButton stdRadio;
    private javax.swing.JPanel studentsRec;
    private javax.swing.JButton submit;
    private javax.swing.JButton submitLecs;
    private javax.swing.JTextField tnumber;
    private javax.swing.JTextField unittf;
    private javax.swing.JTextField userPass;
    private javax.swing.JTextField usernametf;
    private javax.swing.JTextField ussertf;
    private javax.swing.JLabel viewlecs;
    private javax.swing.JLabel viewstnts;
    // End of variables declaration//GEN-END:variables
}
